### ISSUE TITLE
Data in structured format?

### ISSUE THREAD

**Issue by fnoop** [horshack-dpreview/RollingShutter#1]
Hi, thanks very much for this great project :)

It's really fantastic that you're publishing the data for this.  Would you be open to adding the data in a more structured format, like xml or json?  This would be very useful for using the data in other projects, if that's something you would be open to?

**Comment by horshack-dpreview** [comment]
Sure, I'll add it to my to-do list.

**Comment by horshack-dpreview** [comment]
@fnoop I just added json results to the project at:

[https://github.com/horshack-dpreview/RollingShutter/blob/main/results/full_sensor.json](url)
